# Generated by Django 2.0.1 on 2018-01-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0020_systemjump'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField(db_index=True)),
                ('alliance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='core.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('alliance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='core.Alliance')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='corporation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.Corporation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporation',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='core.Alliance'),
        ),
        migrations.AddField(
            model_name='killmail',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='core.Character'),
        ),
        migrations.AddField(
            model_name='killmail',
            name='corporation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='core.Corporation'),
        ),
        migrations.AddField(
            model_name='killmail',
            name='ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attackers_ship', to='sde.Type'),
        ),
        migrations.AddField(
            model_name='killmail',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='sde.System'),
        ),
        migrations.AddField(
            model_name='killmail',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attackers_weapon', to='sde.Type'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='core.Character'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='corporation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='core.Corporation'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='kill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='core.Killmail'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim_ship', to='sde.Type'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim_weapon', to='sde.Type'),
        ),
    ]
