# Generated by Django 2.0.1 on 2018-01-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180126_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliance',
            name='is_closed',
        ),
    ]
