# Generated by Django 2.0.1 on 2018-01-26 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_alliance_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporation',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
