# Generated by Django 2.0.1 on 2018-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180126_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='killmail',
            name='damage',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='killmail',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='killmail',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='killmail',
            name='z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
