# Generated by Django 2.0.1 on 2018-01-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180126_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killmail',
            name='weapon',
        ),
    ]
