# Generated by Django 2.0.1 on 2018-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_killmail_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='founded',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
