# Generated by Django 2.0.1 on 2018-01-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0020_systemjump'),
        ('core', '0007_auto_20180126_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('singleton', models.BooleanField()),
                ('flag', models.IntegerField()),
                ('kill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Killmail')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_items', to='sde.Type')),
            ],
        ),
        migrations.AddField(
            model_name='attacker',
            name='final_blow',
            field=models.BooleanField(default=False),
        ),
    ]
