# Generated by Django 2.0.1 on 2018-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180126_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='singleton',
            field=models.IntegerField(),
        ),
    ]
