# Generated by Django 2.0.1 on 2018-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180126_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created',
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='created',
        ),
        migrations.AddField(
            model_name='character',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
