# Generated by Django 2.0.1 on 2018-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180129_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killmail',
            name='x',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='killmail',
            name='y',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='killmail',
            name='z',
            field=models.FloatField(default=None, null=True),
        ),
    ]
