# Generated by Django 2.0.1 on 2018-02-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180131_1454'),
    ]

    operations = [
        migrations.RenameModel('Attacker', 'Involved')
    ]
