# Generated by Django 2.0.1 on 2018-02-02 11:23

from django.db import migrations


def forwards_func(apps, schema_editor):
    Killmail = apps.get_model("core", "Killmail")
    Involved = apps.get_model("core", "Involved")

    for km in Killmail.objects.all():
        Involved(
            kill=km,
            character=km.character,
            corporation=km.corporation,
            alliance=km.alliance,
            attacker=False,
            ship=km.ship,
            damage=0
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180202_1122'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
