# Generated by Django 2.0.1 on 2018-02-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180202_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involved',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved', to='core.Alliance'),
        ),
        migrations.AlterField(
            model_name='involved',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved', to='core.Character'),
        ),
        migrations.AlterField(
            model_name='involved',
            name='corporation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved', to='core.Corporation'),
        ),
        migrations.AlterField(
            model_name='involved',
            name='kill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved', to='core.Killmail'),
        ),
    ]
