# Generated by Django 2.0.1 on 2018-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180202_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='killmail',
            name='involved_count',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
