# Generated by Django 2.0.1 on 2018-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_killmail_involved_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killmail',
            name='involved_count',
        ),
        migrations.AddField(
            model_name='killmail',
            name='attackers',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
