# Generated by Django 2.0.1 on 2018-05-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0021_auto_20180206_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='sun',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
    ]
